name: terraform-docs

on:
  push:
    branches: [main]
    paths:
      - 'modules/**/*.tf'

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Generate module READMEs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: modules/kms,modules/s3-baseline,modules/cloudtrail
          output-file: README.md
          output-method: inject
          git-push: "false"   # we'll PR instead

      - name: Open PR with updated module docs
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: auto-update module READMEs"
          title: "docs: auto-update module READMEs"
          body: |
            Automated update of module READMEs by terraform-docs.

            Reviewed by CI. Safe to merge if all checks pass.
          branch: bot/terraform-docs
          delete-branch: true
          add-paths: modules/**/README.mdubu